### ISSUE TITLE
support for sending additional data?

### ISSUE THREAD

**Issue by filippog** [Yipit/cron-sentry#16]
hi,
thanks for keep maintaining cron-sentry!
I'd find useful to add job-specific `data` when using cron-sentry, is it something you'd consider adding? happy to try it too and submit a PR but wanted to know what you think first

thanks!
filippo

**Comment by filippog** [comment]
hi!
thoughts on this?

**Comment by hltbra** [comment]
Hi @filippog, I missed this issue before. The other day I thought about this feature but didn't stop to write the code. What are you thinking? I would be more than happy to review a pull request.

Thanks

**Comment by filippog** [comment]
hi @hltbra,
what I had in mind is something from the environment like in #18!
Additionally the prefix might be configured too? Using the commandline might have been harder since this ends in crontabs usually.

**Comment by filippog** [comment]
hi @hltbra thoughts on this and related #18 ?

**Comment by hltbra** [comment]
@filippog: I will get back to you tomorrow with a solution.

**Comment by filippog** [comment]
#18 is merged, closing
